//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSystem.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSystem.Resource.Resource_zh", typeof(Resource_zh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 多轴联动 的本地化字符串。
        /// </summary>
        internal static string Btn_AllAxisMove_Text {
            get {
                return ResourceManager.GetString("Btn_AllAxisMove.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用点位 的本地化字符串。
        /// </summary>
        internal static string Btn_Apply_Text {
            get {
                return ResourceManager.GetString("Btn_Apply.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 静音 的本地化字符串。
        /// </summary>
        internal static string Btn_CloseBuzzer_Text {
            get {
                return ResourceManager.GetString("Btn_CloseBuzzer.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        internal static string Btn_Connect_Text {
            get {
                return ResourceManager.GetString("Btn_Connect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录点位 的本地化字符串。
        /// </summary>
        internal static string Btn_Record_Text {
            get {
                return ResourceManager.GetString("Btn_Record.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        internal static string Btn_Reset_Text {
            get {
                return ResourceManager.GetString("Btn_Reset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单轴点动 的本地化字符串。
        /// </summary>
        internal static string Btn_SingleAxisMove_Text {
            get {
                return ResourceManager.GetString("Btn_SingleAxisMove.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态 的本地化字符串。
        /// </summary>
        internal static string Btn_Status_Title_Text {
            get {
                return ResourceManager.GetString("Btn_Status_Title.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Btn_Stop_Text {
            get {
                return ResourceManager.GetString("Btn_Stop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓1 的本地化字符串。
        /// </summary>
        internal static string Column_Bin1_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin1.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓2 的本地化字符串。
        /// </summary>
        internal static string Column_Bin2_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin2.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓3 的本地化字符串。
        /// </summary>
        internal static string Column_Bin3_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin3.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓4 的本地化字符串。
        /// </summary>
        internal static string Column_Bin4_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin4.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓5 的本地化字符串。
        /// </summary>
        internal static string Column_Bin5_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin5.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓6 的本地化字符串。
        /// </summary>
        internal static string Column_Bin6_HeaderText {
            get {
                return ResourceManager.GetString("Column_Bin6.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string Column_Index_HeaderText {
            get {
                return ResourceManager.GetString("Column_Index.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABCD 无料 的本地化字符串。
        /// </summary>
        internal static string Label_ABCD_Absent_Text {
            get {
                return ResourceManager.GetString("Label_ABCD_Absent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABCD 有料 的本地化字符串。
        /// </summary>
        internal static string Label_ABCD_Exist_Text {
            get {
                return ResourceManager.GetString("Label_ABCD_Exist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前皿/总数 的本地化字符串。
        /// </summary>
        internal static string Label_Index_Text {
            get {
                return ResourceManager.GetString("Label_Index.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样本信息 的本地化字符串。
        /// </summary>
        internal static string Label_Info_Text {
            get {
                return ResourceManager.GetString("Label_Info.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前产品: 的本地化字符串。
        /// </summary>
        internal static string Label_Pdt_Text {
            get {
                return ResourceManager.GetString("Label_Pdt.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行时间 的本地化字符串。
        /// </summary>
        internal static string Label_Span_Text {
            get {
                return ResourceManager.GetString("Label_Span.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string Label_Start_Time_Text {
            get {
                return ResourceManager.GetString("Label_Start_Time.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A&apos;D2 无料 的本地化字符串。
        /// </summary>
        internal static string Lb_AD2_Absent_Text {
            get {
                return ResourceManager.GetString("Lb_AD2_Absent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A&apos;D2 有料 的本地化字符串。
        /// </summary>
        internal static string Lb_AD2_Exist_Text {
            get {
                return ResourceManager.GetString("Lb_AD2_Exist.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态 的本地化字符串。
        /// </summary>
        internal static string Lbl_CurrState_Text {
            get {
                return ResourceManager.GetString("Lbl_CurrState.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 的本地化字符串。
        /// </summary>
        internal static string Node_Device_Text {
            get {
                return ResourceManager.GetString("Node_Device.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string Node_Home_Text {
            get {
                return ResourceManager.GetString("Node_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        internal static string Node_Param_Text {
            get {
                return ResourceManager.GetString("Node_Param.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工站 的本地化字符串。
        /// </summary>
        internal static string Node_Station_Text {
            get {
                return ResourceManager.GetString("Node_Station.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string Page_In_Text {
            get {
                return ResourceManager.GetString("Page_In.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        internal static string Page_Out_Text {
            get {
                return ResourceManager.GetString("Page_Out.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景1 的本地化字符串。
        /// </summary>
        internal static string RB_Scene1_Text {
            get {
                return ResourceManager.GetString("RB_Scene1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景2 的本地化字符串。
        /// </summary>
        internal static string RB_Scene2_Text {
            get {
                return ResourceManager.GetString("RB_Scene2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误日志 的本地化字符串。
        /// </summary>
        internal static string TabPage_Error_Log_Text {
            get {
                return ResourceManager.GetString("TabPage_Error_Log.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行日志 的本地化字符串。
        /// </summary>
        internal static string TabPage_Running_Log_Text {
            get {
                return ResourceManager.GetString("TabPage_Running_Log.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 料仓状态 的本地化字符串。
        /// </summary>
        internal static string TabPage_Status_Text {
            get {
                return ResourceManager.GetString("TabPage_Status.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景选择 的本地化字符串。
        /// </summary>
        internal static string Title_Scene_Text {
            get {
                return ResourceManager.GetString("Title_Scene.Text", resourceCulture);
            }
        }
    }
}
